name: Generate Audiogram

on:
  schedule:
    - cron: '0 10 * * 2'  # martedi alle 10:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: self-hosted
    timeout-minutes: 120

    steps:
      - name: Genera audiogram
        run: |
          cd $HOME/PycharmProjects/podcast-audiogram-generator
          .venv/bin/python -m audiogram_generator --limit 3
